fullnameOverride: service1
replicaCount: 2
port: 20221

imagePullSecretsName: "default-registry-secret"

image:
  repository: "koderover.tencentcloudcr.com/koderover-demo/service1"
  tag: "latest"

resources:
  requests:
    cpu: 10m
    mem: 10Mi

  limits:
    cpu: 20m
    mem: 20Mi
